### ISSUE TITLE
git coco pr fails when using HTTPS (GRC) with profile in remote url

### ISSUE THREAD

**Issue by ryansonshine** [awslabs/git-coco#1]
When using a profile name in the remote url for a repository while using HTTPS (GRC)

```sh
git clone codecommit://CodeCommitProfile@MyDemoRepo my-demo-repo
```

This causes an issue with the `git coco pr` command since it pulls in the profile name and assigns it to the `$repo` variable.

```
An error occurred (InvalidRepositoryNameException) when calling the CreatePullRequest operation: The repository name is not valid. Repository names can be any valid combination of letters, numbers, periods, underscores, and dashes between 1 and 100 characters in length. Names are case sensitive. For more information, see Limits in the AWS CodeCommit User Guide.
https://console.aws.amazon.com/codesuite/codecommit/repositories/CodeCommitProfile@MyDemoRepo/pull-requests//changes
```

**Comment by ctd** [comment]
Thanks for reporting this issue.

I believe git-coco wasn't written with git-remote-codecommit in mind at the time, so it doesn't properly parse  `codecommit://` style URLs. Adding support shouldn't be difficult, I'll take a look at it when I have some time.
