### ISSUE TITLE
git coco create does not work. @qumei

### ISSUE THREAD

**Issue by zqumei0** [awslabs/git-coco#2]
When using git create it errors out.
```git coco create test-repo "Example Description"```

Description does not get passed into the create function and fails the argument check.
```Usage: git coco create <repo> <description>```

The description variable in the codecommit command also need to be wrapped in quotation marks to prevent only the first word from being submitted as the description.

**Comment by zqumei0** [comment]
Created a pull request to resolve this issue. #3

**Comment by rkeene** [comment]
Fixed by #3
